/**
 * 10 named pixel building sprites ported verbatim from
 * `reference/buildings.jsx`. The first 9 are placed across the
 * foreground cityscape (CAFE PIXEL → INK STORE); the 10th
 * (NEON TOWER) lives in the distant skyline.
 *
 * Each sprite is a multi-line char-grid; the palette maps single
 * characters to hex colors. Reference renders these at scale 2.6–3.0
 * with weather + time tints layered on top.
 */

import type { Palette } from "@/lib/pixel/sprite";

export interface BuildingDef {
  readonly key: string;
  readonly name: string;
  /** i18n key in `messages/<locale>/town.json` (e.g. "cafe", "studyHall"). */
  readonly labelKey: string;
  readonly sprite: string;
  readonly palette: Palette;
  /** Reference render scale — kept here so callers can use the same scaling. */
  readonly scale: number;
  /** Hex used by the radial-glow halo behind the building at night. */
  readonly glowColor: string;
}

const B_CAFE: BuildingDef = {
  key: "cafe",
  name: "CAFE PIXEL",
  labelKey: "cafe",
  sprite: `
.............CC.............
............CCCC............
.............CC.............
.............CC.............
....AAAAAAAAAAAAAAAAAA......
...AAAAAAAAAAAAAAAAAAAA.....
..MMMMMMMMMMMMMMMMMMMMMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MMMMMMMMMMMMMMMMMMMMMM....
..AA##AA##AA##AA##AA##AA....
..A####A####A####A####AA....
..MWWWMMWWWMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..PPPPPPPPPPPPPPPPPPPPPP....
..PYYYPYYYPYYYPYYYPYYYPP....
..PPPPPPPPPPPPPPPPPPPPPP....
.PPPPPPPPPPPPPPPPPPPPPPPP...
`,
  palette: {
    C: "#4a2a1a", A: "#dc2626", M: "#3a2820", R: "#fcd34d",
    "#": "#fbbf24", W: "#a78bfa", N: "#0a0524", P: "#0a0524", Y: "#fbbf24",
  },
  scale: 2.8,
  glowColor: "#fcd34d",
};

const B_STUDY: BuildingDef = {
  key: "study",
  name: "STUDY HALL",
  labelKey: "studyHall",
  sprite: `
........YYYYYYYY........
.......YY......YY.......
......YY..AAAA..YY......
.....YY..AHHHHA..YY.....
....YYYYAHHHHHHAYYYY....
....SSSSSSSSSSSSSSS.....
....S..............S....
....S.RR..RR..RR..RR....
....S.RR..RR..RR..RRS...
....S..............S....
....S.RR..RR..RR..RRS...
....S.RR..RR..RR..RRS...
....S..............S....
....S.NN..NN..NN..NNS...
....S.NN..NN..NN..NNS...
....SBBBBBBBBBBBBBBBS...
....SBBBBBOOOOBBBBBSS...
....SBBBBBOOOOBBBBBBS...
....BBBBBBBBBBBBBBBBBB..
....BBBBBBBBBBBBBBBBBB..
`,
  palette: {
    Y: "#a78bfa", A: "#fcd34d", H: "#0a0524", S: "#7c6f9e",
    R: "#fef9c3", N: "#a78bfa", B: "#5a4a7a", O: "#fcd34d",
  },
  scale: 3.0,
  glowColor: "#a78bfa",
};

const B_LOFI: BuildingDef = {
  key: "lofi",
  name: "LOFI BAR",
  labelKey: "lofiBar",
  sprite: `
.........MMMMMM..........
........MM####MM.........
.......MM######MM........
......MM########MM.......
.....MMMMMMMMMMMMMM......
.....MMMMMMMMMMMMMM......
....MNNNNNNNNNNNNNNM.....
....MN##NN######NN#NM....
....MN##NN######NN#NM....
....MNNNNNNNNNNNNNNM.....
....MEEEEEEEEEEEEEEM.....
....ME##EE######EE##M....
....ME##EE######EE##M....
....MEEEEEEEEEEEEEEM.....
....MMMMMMMMMMMMMMMMM....
....MQQQQQQQQQQQQQQQM....
....MQLOFIQBARQLIVEQM....
....MQQQQQQQQQQQQQQQM....
....MNNNNNNNNNNNNNNNM....
....MNNDDDNNDDDNNDDDM....
....MBBBBBBBBBBBBBBBM....
`,
  palette: {
    M: "#3a1a4a", "#": "#22d3ee", E: "#1a0d3d",
    N: "#5a2a6a", "Q": "#ec4899", D: "#fcd34d",
    B: "#0a0524", L: "#ec4899",
  },
  scale: 2.8,
  glowColor: "#ec4899",
};

const B_ARCADE: BuildingDef = {
  key: "arcade",
  name: "PIXEL ARCADE",
  labelKey: "arcade",
  sprite: `
.MMMMMMMMMMMMMMMMMMMMMM.
.M####################M.
.M#AARCADEAARRRAACAA##M.
.M####################M.
.MMMMMMMMMMMMMMMMMMMMMM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNNNNNNNDDDDDNNNNNNNNM.
.MNNNNNNNDOODNNNNNNNNNM.
.MBBBBBBBBBBBBBBBBBBBBM.
`,
  palette: {
    M: "#1a0d3d", "#": "#22d3ee", A: "#ec4899",
    R: "#f0abfc", C: "#fcd34d", Y: "#22d3ee",
    N: "#0a0524", D: "#1a0d3d", O: "#fcd34d", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#22d3ee",
};

const B_RAMEN: BuildingDef = {
  key: "ramen",
  name: "NEKO RAMEN",
  labelKey: "ramen",
  sprite: `
.....RRRRRRRRRRRRR......
....RRRRRRRRRRRRRRR.....
...RRRRRRRRRRRRRRRRR....
..RRRRRRRRRRRRRRRRRRR...
..RRRRRRRRRRRRRRRRRRR...
...PPPPPPPPPPPPPPPPP....
....OOOOOOOOOOOOOOO.....
....OYO.OYO.OYO.OYO.....
....OYO.OYO.OYO.OYO.....
....OOO.OOO.OOO.OOO.....
...MMMMMMMMMMMMMMMMM....
...MQNEKOQRAMENQLITQM...
...MMMMMMMMMMMMMMMMMM...
...MWWMMWWMMWWMMWWMMM...
...MWNMMWWMMWWMMWNMMM...
...MWWMMWWMMWWMMWWMMM...
...MMMMMDDDDDMMMMMMMM...
...MMMMMDOODDMMMMMMMM...
...BBBBBBBBBBBBBBBBBB...
`,
  palette: {
    R: "#7c1d3a", P: "#0a0524", O: "#fbbf24", Y: "#dc2626",
    M: "#fef9c3", "Q": "#dc2626", W: "#0a0524", N: "#fef9c3",
    D: "#7c1d3a", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#fef9c3",
};

const B_LIBRARY: BuildingDef = {
  key: "library",
  name: "LIBRARY",
  labelKey: "library",
  sprite: `
..........DD..........
.........DDDD.........
........DDDDDD........
.......DDDDDDDD.......
......DDPPPPPPDD......
....SSSPPPPPPPPSS.....
....SSSSSSSSSSSSS.....
...SSAAAAAAAAAAASS....
...SSAAAAAAAAAAASS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSSSSSSSSSSSSSS....
...SSSSDDDDDDDSSSSS...
...SSSSDOOOODSSSSSS...
...BBBBBBBBBBBBBBBB...
`,
  palette: {
    D: "#a78bfa", P: "#fcd34d", S: "#d6c5e8", A: "#7c6f9e",
    C: "#fcd34d", O: "#dc2626", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#a78bfa",
};

const B_CWORK: BuildingDef = {
  key: "cwork",
  name: "COWORKING",
  labelKey: "coworking",
  sprite: `
.....TTTTTTTTTTTT......
.....TTTTTTTTTTTT......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....NNNDDDDDDNNNN.....
.....NNNDOOODONNNN.....
.....BBBBBBBBBBBBB.....
`,
  palette: {
    T: "#22d3ee", G: "#1a0d3d", "#": "#67e8f9",
    N: "#0a0524", D: "#3a2a5a", O: "#fcd34d", B: "#0a0524",
  },
  scale: 2.6,
  glowColor: "#22d3ee",
};

const B_GAL: BuildingDef = {
  key: "gallery",
  name: "GALLERY",
  labelKey: "gallery",
  sprite: `
..........QQ..........
..........QQ..........
..........QQ..........
.........QQQQ.........
.........QQQQ.........
........MMMMMM........
.......MMNNMMMMM......
......MMNNNNMMMMM.....
.....MMNNNNNNMMMMM....
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MMMMMQQQQQMMMMM...
....MMMMMQARTQMMMMM...
....MMMMMQQQQQMMMMM...
....MMMMDDDDDDMMMMM...
....MMMMDOOOODMMMMM...
....BBBBBBBBBBBBBBB...
`,
  palette: {
    "Q": "#ec4899", M: "#2a1854", N: "#a78bfa",
    W: "#fbbf24", D: "#0a0524", O: "#22d3ee", B: "#0a0524",
  },
  scale: 2.6,
  glowColor: "#ec4899",
};

const B_INK: BuildingDef = {
  key: "ink",
  name: "INK STORE",
  labelKey: "inkStore",
  sprite: `
......CCCCCCCCCC......
.....CCCCCCCCCCCC.....
....AAAAAAAAAAAAAA....
....AAAAAAAAAAAAAA....
...MMMMMMMMMMMMMMM....
...MQQQQQQQQQQQQQM....
...MQINKQSTOREQQQM....
...MQQQQQQQQQQQQQM....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMMMMMMMMMMM....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMDDDDDMMMMM....
...MMMMMDOODOMMMMM....
...BBBBBBBBBBBBBBB....
`,
  palette: {
    C: "#fcd34d", A: "#6d28d9", M: "#3a2820",
    "Q": "#fbbf24", W: "#fef9c3", D: "#0a0524", O: "#fcd34d", B: "#0a0524",
  },
  scale: 2.6,
  glowColor: "#fcd34d",
};

/**
 * 9-building cityscape, exact reference order (CAFE → INK STORE).
 * `Cityscape` consumes this array directly with `flex space-between`.
 */
export const BUILDINGS: readonly BuildingDef[] = [
  B_CAFE,
  B_STUDY,
  B_LOFI,
  B_ARCADE,
  B_RAMEN,
  B_LIBRARY,
  B_CWORK,
  B_GAL,
  B_INK,
];
