/**
 * 5 named pixel building sprites used across the foreground cityscape
 * (CAFE PIXEL, LOFI BAR, PIXEL ARCADE, NEKO RAMEN, LIBRARY). Each
 * sprite is a multi-line char-grid; the palette maps single characters
 * to hex colors. Reference renders these at scale 2.6–3.0 with weather
 * and time tints layered on top.
 */

import type { Palette } from "@/lib/pixel/sprite";

export interface BuildingDef {
  readonly key: string;
  readonly name: string;
  /** i18n key in `messages/<locale>/town.json` (e.g. "cafe", "studyHall"). */
  readonly labelKey: string;
  readonly sprite: string;
  readonly palette: Palette;
  /** Reference render scale — kept here so callers can use the same scaling. */
  readonly scale: number;
  /** Hex used by the radial-glow halo behind the building at night. */
  readonly glowColor: string;
}

const B_CAFE: BuildingDef = {
  key: "cafe",
  name: "CAFE PIXEL",
  labelKey: "cafe",
  sprite: `
.............CC.............
............CCCC............
.............CC.............
.............CC.............
....AAAAAAAAAAAAAAAAAA......
...AAAAAAAAAAAAAAAAAAAA.....
..MMMMMMMMMMMMMMMMMMMMMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MMMMMMMMMMMMMMMMMMMMMM....
..AA##AA##AA##AA##AA##AA....
..A####A####A####A####AA....
..MWWWMMWWWMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..PPPPPPPPPPPPPPPPPPPPPP....
..PYYYPYYYPYYYPYYYPYYYPP....
..PPPPPPPPPPPPPPPPPPPPPP....
.PPPPPPPPPPPPPPPPPPPPPPPP...
`,
  palette: {
    C: "#4a2a1a", A: "#dc2626", M: "#3a2820", R: "#fcd34d",
    "#": "#fbbf24", W: "#a78bfa", N: "#0a0524", P: "#0a0524", Y: "#fbbf24",
  },
  scale: 2.8,
  glowColor: "#fcd34d",
};

const B_LOFI: BuildingDef = {
  key: "lofi",
  name: "LOFI BAR",
  labelKey: "lofiBar",
  sprite: `
.........MMMMMM..........
........MM####MM.........
.......MM######MM........
......MM########MM.......
.....MMMMMMMMMMMMMM......
.....MMMMMMMMMMMMMM......
....MNNNNNNNNNNNNNNM.....
....MN##NN######NN#NM....
....MN##NN######NN#NM....
....MNNNNNNNNNNNNNNM.....
....MEEEEEEEEEEEEEEM.....
....ME##EE######EE##M....
....ME##EE######EE##M....
....MEEEEEEEEEEEEEEM.....
....MMMMMMMMMMMMMMMMM....
....MQQQQQQQQQQQQQQQM....
....MQLOFIQBARQLIVEQM....
....MQQQQQQQQQQQQQQQM....
....MNNNNNNNNNNNNNNNM....
....MNNDDDNNDDDNNDDDM....
....MBBBBBBBBBBBBBBBM....
`,
  palette: {
    M: "#3a1a4a", "#": "#22d3ee", E: "#1a0d3d",
    N: "#5a2a6a", "Q": "#ec4899", D: "#fcd34d",
    B: "#0a0524", L: "#ec4899",
  },
  scale: 2.8,
  glowColor: "#ec4899",
};

const B_ARCADE: BuildingDef = {
  key: "arcade",
  name: "PIXEL ARCADE",
  labelKey: "arcade",
  sprite: `
.MMMMMMMMMMMMMMMMMMMMMM.
.M####################M.
.M#AARCADEAARRRAACAA##M.
.M####################M.
.MMMMMMMMMMMMMMMMMMMMMM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNNNNNNNDDDDDNNNNNNNNM.
.MNNNNNNNDOODNNNNNNNNNM.
.MBBBBBBBBBBBBBBBBBBBBM.
`,
  palette: {
    M: "#1a0d3d", "#": "#22d3ee", A: "#ec4899",
    R: "#f0abfc", C: "#fcd34d", Y: "#22d3ee",
    N: "#0a0524", D: "#1a0d3d", O: "#fcd34d", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#22d3ee",
};

const B_RAMEN: BuildingDef = {
  key: "ramen",
  name: "NEKO RAMEN",
  labelKey: "ramen",
  sprite: `
.....RRRRRRRRRRRRR......
....RRRRRRRRRRRRRRR.....
...RRRRRRRRRRRRRRRRR....
..RRRRRRRRRRRRRRRRRRR...
..RRRRRRRRRRRRRRRRRRR...
...PPPPPPPPPPPPPPPPP....
....OOOOOOOOOOOOOOO.....
....OYO.OYO.OYO.OYO.....
....OYO.OYO.OYO.OYO.....
....OOO.OOO.OOO.OOO.....
...MMMMMMMMMMMMMMMMM....
...MQNEKOQRAMENQLITQM...
...MMMMMMMMMMMMMMMMMM...
...MWWMMWWMMWWMMWWMMM...
...MWNMMWWMMWWMMWNMMM...
...MWWMMWWMMWWMMWWMMM...
...MMMMMDDDDDMMMMMMMM...
...MMMMMDOODDMMMMMMMM...
...BBBBBBBBBBBBBBBBBB...
`,
  palette: {
    R: "#7c1d3a", P: "#0a0524", O: "#fbbf24", Y: "#dc2626",
    M: "#fef9c3", "Q": "#dc2626", W: "#0a0524", N: "#fef9c3",
    D: "#7c1d3a", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#fef9c3",
};

const B_LIBRARY: BuildingDef = {
  key: "library",
  name: "LIBRARY",
  labelKey: "library",
  sprite: `
..........DD..........
.........DDDD.........
........DDDDDD........
.......DDDDDDDD.......
......DDPPPPPPDD......
....SSSPPPPPPPPSS.....
....SSSSSSSSSSSSS.....
...SSAAAAAAAAAAASS....
...SSAAAAAAAAAAASS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSSSSSSSSSSSSSS....
...SSSSDDDDDDDSSSSS...
...SSSSDOOOODSSSSSS...
...BBBBBBBBBBBBBBBB...
`,
  palette: {
    D: "#a78bfa", P: "#fcd34d", S: "#d6c5e8", A: "#7c6f9e",
    C: "#fcd34d", O: "#dc2626", B: "#0a0524",
  },
  scale: 2.8,
  glowColor: "#a78bfa",
};

/**
 * 5-building cityscape (CAFE → LIBRARY). Trimmed from the original
 * 9-building lineup to keep the foreground readable — `NamedBuildings`
 * consumes this array directly with `flex space-between`.
 */
export const BUILDINGS: readonly BuildingDef[] = [
  B_CAFE,
  B_LOFI,
  B_ARCADE,
  B_RAMEN,
  B_LIBRARY,
];
