/**
 * Auto-generated by `pnpm gen:api` (openapi-typescript).
 * Hand-written stubs below are the MVP surface — rerun the generator after
 * the backend `/openapi.json` is reachable to replace them with the full
 * paths/operations map.
 */

export type User = {
  id: string;
  email: string;
  display_name: string;
  character_key: string | null;
  role_label: string | null;
};

export type Tokens = {
  access_token: string;
  refresh_token: string;
  token_type: "bearer";
};

export type AuthResponse = {
  user: User;
  tokens: Tokens;
};

export type FocusSessionMode = "focus" | "short" | "long";
export type FocusSessionStatus = "active" | "completed" | "abandoned" | "cancelled";

export type FocusSession = {
  id: string;
  user_id: string;
  partner_user_id: string | null;
  mode: FocusSessionMode;
  duration_seconds: number;
  elapsed_seconds: number;
  remaining_seconds: number;
  status: FocusSessionStatus;
  task_label: string | null;
  started_at: string;
  ended_at: string | null;
};

export type Note = {
  id: string;
  title: string;
  body: string;
  done: boolean;
  created_at: string;
  updated_at: string;
};

export type Match = {
  id: string;
  requester_id: string;
  candidate_id: string;
  compatibility: number;
  reason: string;
  status: "pending" | "accepted" | "skipped" | "expired";
  created_at: string;
};

export type LeaderboardEntry = {
  user_id: string;
  display_name: string;
  character_key: string | null;
  completed_count: number;
};

export type Achievement = {
  code: string;
  icon: string;
  title: string;
  description: string;
};

export type ShopItem = {
  id: string;
  category: string;
  icon: string;
  name: string;
  description: string;
  price_cents: number;
  featured: boolean;
};
