/**
 * Auto-generated by `pnpm gen:api` (openapi-typescript).
 * Hand-written stubs below are the MVP surface — rerun the generator after
 * the backend `/openapi.json` is reachable to replace them with the full
 * paths/operations map.
 */

// Phase 3: visual attrs of an equipped vehicle (only set when the user has
// equipped a `car` shop item). Sourced from `shop_items.render_meta`.
export type VehicleRenderMeta = {
  icon: string;
  body_color: string;
  roof_color: string;
};

export type User = {
  id: string;
  email: string;
  display_name: string;
  character_key: string | null;
  role_label: string | null;
  marketing_opt_in?: boolean;
  equipped_vehicle_item_id: string | null;
  equipped_vehicle: VehicleRenderMeta | null;
};

export type Tokens = {
  access_token: string;
  refresh_token: string;
  token_type: "bearer";
};

export type AuthResponse = {
  user: User;
  tokens: Tokens;
};

export type FocusSessionMode = "focus" | "short" | "long";
export type FocusSessionStatus = "active" | "completed" | "abandoned" | "cancelled";

export type FocusSession = {
  id: string;
  user_id: string;
  partner_user_id: string | null;
  mode: FocusSessionMode;
  duration_seconds: number;
  elapsed_seconds: number;
  remaining_seconds: number;
  status: FocusSessionStatus;
  task_label: string | null;
  started_at: string;
  ended_at: string | null;
};

export type Note = {
  id: string;
  title: string;
  body: string;
  done: boolean;
  created_at: string;
  updated_at: string;
};

export type Match = {
  id: string;
  requester_id: string;
  candidate_id: string;
  // Hydrated server-side so the focus room and modal can render character
  // sprites for both sides without a second round-trip. Null when that side
  // has not picked a character yet.
  requester_character_key: string | null;
  candidate_character_key: string | null;
  compatibility: number;
  reason: string;
  status: "pending" | "accepted" | "skipped" | "expired";
  created_at: string;
};

export type LeaderboardEntry = {
  user_id: string;
  display_name: string;
  character_key: string | null;
  completed_count: number;
};

export type Achievement = {
  code: string;
  icon: string;
  title: string;
  description: string;
};

export type ShopItemPrice = {
  currency_code: string;       // "T" | "TWD" | ...
  amount_minor: number;        // integer in minor units (T -> centiT, TWD -> NTD cents)
};

export type ShopItem = {
  id: string;
  category: string;
  icon: string;
  name: string;
  description: string;
  price_cents: number;          // legacy field — kept for backward compat
  featured: boolean;
  prices: ShopItemPrice[];      // Phase 2: multi-currency prices
};

export type StreetUser = {
  id: string;
  display_name: string;
  character_key: string | null;
  status: string;
  vehicle: VehicleRenderMeta | null;
};

// Phase 3: response from PUT /api/v1/me/equipment
export type EquipmentResponse = {
  equipped_vehicle_item_id: string | null;
  equipped_vehicle: VehicleRenderMeta | null;
};

// ── Phase 2: wallet + items ────────────────────────────────────────────────
export type Wallet = {
  currency_code: string;
  balance_minor: number;
};

export type WalletTransaction = {
  id: string;
  currency_code: string;
  delta_minor: number;
  reason: string;
  ref_type: string | null;
  ref_id: string | null;
  balance_after_minor: number;
  created_at: string;
};

export type UserItem = {
  id: string;
  shop_item_id: string;
  acquired_via: string;
  acquired_at: string;
};

export type PurchaseResponse = {
  item_id: string;
  transaction_id: string;
  currency_code: string;
  new_balance_minor: number;
  delta_minor: number;
  acquired_at: string;
};

// ── Phase 4: rooms ─────────────────────────────────────────────────────────
// Mirrors backend ALLOWED_THEMES (frozenset in app/domain/models/room.py);
// keep this list in sync with frontend/lib/data/scenes.ts SCENES keys.
export type RoomTheme =
  | "dawn"
  | "day"
  | "dusk"
  | "night"
  | "rain"
  | "snow"
  | "storm";

export type RoomVisibility = "public" | "invite_only";

export type Room = {
  id: string;
  owner_user_id: string;
  name: string;
  theme: RoomTheme;
  visibility: RoomVisibility;
  max_visitors: number;
  created_at: string;
  updated_at: string;
};

// ── Phase 5: room decoration items ─────────────────────────────────────────
// One row per placement inside a room. `x` and `y` are integer percentages
// (0–100) of the room interior bounding box, kept resolution-independent so
// the same data renders identically across viewport sizes.
export type RoomItem = {
  id: string;
  room_id: string;
  user_item_id: string;
  x: number;
  y: number;
  z_index: number;
  created_at: string;
  updated_at: string;
};

export type PlaceRoomItemInput = {
  user_item_id: string;
  x: number;
  y: number;
};

export type MoveRoomItemInput = {
  x: number;
  y: number;
};

// ── Phase 9: shared playback timeline ──────────────────────────────────────
// Server-authoritative timeline; timestamps are epoch milliseconds so the
// frontend's drift loop can do plain Date.now() arithmetic. ``track`` is
// denormalized so a freshly-joining visitor doesn't have to round-trip to
// the track lookup endpoint just to render "Now playing — {title}".
export type RoomPlayback = {
  id: string;
  room_id: string;
  current_track_id: string | null;
  started_at_ms: number | null;
  paused_at_ms: number | null;
  is_playing: boolean;
  track: Track | null;
};

export type PlaybackChangeInput = {
  track_id: string;
};

// ── Phase 8: room visitor sessions ─────────────────────────────────────────
// One row per active "user X is currently in room Y". Server enforces
// max_visitors (visibility-aware: owner bypasses the cap). The frontend
// drives visit/leave on room page mount/unmount; abrupt browser-close
// scenarios leave a stale row for a future cleanup job to reap.
export type RoomVisit = {
  id: string;
  room_id: string;
  visitor_user_id: string;
  joined_at: string;
};

// ── Phase 6 Tier-2: track library ───────────────────────────────────────────
export type TrackMood = "lofi" | "jazz" | "rain" | "ambient";

export type Track = {
  id: string;
  title: string;
  artist: string | null;
  mood: string;                 // TrackMood at the edge; string in transport
  duration_ms: number | null;
  content_type: string;
  file_size_bytes: number;
  license: string | null;
  uploaded_by_user_id: string;
  created_at: string;
};

export type AddRoomTrackRequest = {
  track_id: string;
};

export type RoomTrack = {
  id: string;
  room_id: string;
  track_id: string;
  position: number;
  track: Track;
};
